# Generated by Django 3.0.4 on 2020-04-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=10)),
                ('harga_beli', models.IntegerField()),
                ('harga_jual', models.IntegerField()),
                ('banyak_barang', models.IntegerField()),
                ('jenis_barang', models.CharField(choices=[('OBAT-OBATAN', 'obat-obatan'), ('MAKANAN DAN MINUMAN RINGAN ', 'makananminuman')], default='lain-lain', max_length=30)),
                ('tgl_beli', models.DateField(auto_now_add=True, null=True)),
                ('tgl_kdlws', models.DateField()),
                ('status', models.CharField(choices=[('ADA', 'ADA'), ('KOSONG', 'KOSONG')], max_length=10)),
            ],
        ),
    ]
