# Generated by Django 3.0.2 on 2020-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=10)),
                ('harga_beli', models.IntegerField()),
                ('harga_jual', models.IntegerField()),
                ('banyak_barang', models.IntegerField()),
                ('status', models.CharField(choices=[('ADA', 'ADA'), ('KOSONG', 'KOSONG')], max_length=10)),
            ],
        ),
    ]
