# Generated by Django 3.0.2 on 2020-04-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelontong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='jenis_barang',
            field=models.CharField(choices=[('OBAT-OBATAN', 'obat-obatan'), ('MAKANAN DAN MINUMAN RINGAN ', 'makananminuman')], default='obat-obatan', max_length=30),
            preserve_default=False,
        ),
    ]
