# Generated by Django 3.0.4 on 2020-05-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelontong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='barangJualan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_jual', models.DateField(auto_now_add=True)),
                ('nama_barang', models.CharField(max_length=10)),
                ('banyak_beli', models.IntegerField()),
            ],
        ),
    ]
