# Generated by Django 3.0.2 on 2020-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelontong', '0002_barang_jenis_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis_barang',
            field=models.CharField(choices=[('OBAT-OBATAN', 'obat-obatan'), ('MAKANAN DAN MINUMAN RINGAN ', 'makananminuman')], default='lain-lain', max_length=30),
        ),
    ]
